[package]
name = "pallet-mandate"
version = "2.0.1"
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
edition = "2018"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/ETeissonniere/pallet-mandate"
description = "A Substrate pallet to help over modules dispatch root calls"

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'sp-runtime/std',
    'sp-io/std',
    'sp-std/std',
    'system/std',
]

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.2.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.6'

[dev-dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.6'
